import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const gilroyRegular = localFont({
  src: "./fonts/Gilroy-Regular.ttf",
  variable: "--font-gilroy-regular",
  weight: "100",
});
const gilroySemiBold = localFont({
  src: "./fonts/Gilroy-SemiBold.ttf",
  variable: "--font-gilroy-semiBold",
  weight: "600",
});
const gilroyBold = localFont({
  src: "./fonts/Gilroy-Bold.ttf",
  variable: "--font-gilroy-bold",
  weight: "700",
});
const gilroyMedium = localFont({
  src: "./fonts/Gilroy-Medium.ttf",
  variable: "--font-gilroy-medium",
  weight: "900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gilroyRegular.variable} ${gilroySemiBold.variable} ${gilroyBold.variable} ${gilroyMedium.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
